### ISSUE TITLE
When window is small, data entry fields for cities are stacked too closely together

### ISSUE THREAD

**Issue by KeetonMartin** [KeetonMartin/routeCards#5]
I think they need some vertical padding from each other or something
<img width="962" alt="Screen Shot 2022-09-17 at 2 51 57 PM" src="https://user-images.githubusercontent.com/25427567/190872223-0af37481-3d37-4af3-928a-390c773dc50f.png">

**Comment by abitsalihu** [comment]
@KeetonMartin I would like to help on this issue. :)

**Comment by keetonatwork** [comment]
> 

Please feel free to open a PR!
